[program:dev-seal-queue]
directory=/var/www/dev/backend/seal
command=/usr/bin/php artisan queue:work --sleep=3 --tries=3 --timeout=90
user=www-data
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/dev-seal-queue.log
stderr_logfile=/var/log/supervisor/dev-seal-queue-error.log
