[program:dev-seal-schedule]
process_name=%(program_name)s
directory=/var/www/dev/backend/seal
command=/usr/bin/php artisan schedule:work
user=www-data
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/dev-seal-schedule.log
stderr_logfile=/var/log/supervisor/dev-seal-schedule-error.log
